import { test, expect } from "@playwright/test";

test("public landing leads with the map and opens provider profiles", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await expect(page.locator(".map-loading")).toHaveCount(0, { timeout: 30000 });
  await expect(page.locator(".map-sidebar input")).toHaveCount(0);
  const mapBox = await page.locator(".landing-map-section").boundingBox();
  const textBox = await page.locator(".landing-intro").boundingBox();
  expect(textBox!.y).toBeGreaterThanOrEqual(mapBox!.y + mapBox!.height);
  await page.getByRole("button", { name: "Zoom in", exact: true }).click();
  await page.getByRole("button", { name: "Reset map", exact: true }).click();
  await page.getByRole("button", { name: "Open map filters" }).click();
  await page.getByLabel("Country", { exact: true }).selectOption("Japan");
  await expect(page.getByText("4 locations", { exact: true })).toBeVisible();
  await expect(page.locator(".geo-media-pin video").first()).toBeVisible();
  await expect(page.getByRole("button", { name: /View .* profile/ }).first()).toBeVisible();
  await page.getByRole("button", { name: "Open map filters" }).click();
  await page.getByRole("button", { name: "How FileMarket protects sourcing" }).click();
  await expect(page.getByRole("heading", { name: /Know who is behind every dataset/ })).toBeInViewport();
  await expect(page.getByText("Escrow payments", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/desktop-light-map.png" });
  expect(errors).toEqual([]);
});

test("signup, saved provider, sample downloads, requests, session persistence, and logout", async ({ page, request }) => {
  const email = `test-${Date.now()}@example.test`;
  const password = "FileMarketTest!2026";
  await page.goto("/signup");
  await page.getByLabel("Full name").fill("Test Explorer");
  await page.getByLabel("Work email").fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/map/);
  await expect(page.getByRole("textbox", { name: "Search geography, companies, or facilities" })).toBeVisible();
  await page.getByRole("textbox", { name: "Search geography, companies, or facilities" }).fill("Tokyo");
  await expect(page.locator(".provider-card")).toHaveCount(4);
  await page.locator(".provider-card").first().click();
  await expect(page.getByRole("button", { name: "Request access", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Save provider", exact: true }).click();
  await expect(page.getByRole("button", { name: "Unsave provider", exact: true })).toBeVisible();
  await page.getByRole("button", { name: /Motion sample/ }).click();
  await expect(page.getByRole("dialog", { name: "Motion data sample" })).toBeVisible();
  await expect(page.locator(".full-sample")).toHaveJSProperty("paused", false);
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: /Point cloud PLY/ }).click();
  await expect(page.getByRole("dialog", { name: "Point cloud preview" })).toBeVisible();
  await page.locator(".pointcloud-viewer canvas").focus();
  await page.keyboard.press("ArrowRight");
  const plyDownload = page.waitForEvent("download");
  await page.getByRole("link", { name: "Download PLY" }).click();
  expect((await plyDownload).suggestedFilename()).toMatch(/demo\.ply$/);
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Request access", exact: true }).click();
  await page.getByLabel("Your use case").fill("Testing robotics perception with synthetic demonstration samples.");
  await page.getByRole("button", { name: "Submit request" }).click();
  await expect(page.getByRole("button", { name: "Access requested" })).toBeDisabled();
  const download = page.waitForEvent("download");
  await page.getByRole("link", { name: "Download sample metadata" }).click();
  expect((await download).suggestedFilename()).toMatch(/demo\.json$/);
  await page.screenshot({ path: "test-results/desktop-profile.png" });
  await page.reload();
  await expect(page.getByRole("textbox", { name: "Search geography, companies, or facilities" })).toBeVisible();
  await page.getByRole("button", { name: "Saved providers", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Your sourcing workspace" })).toBeVisible();
  await expect(page.locator(".saved-grid button")).toHaveCount(1);
  await expect(page.locator(".request-row")).toHaveCount(1);
  await page.screenshot({ path: "test-results/workspace.png" });
  await page.keyboard.press("Escape");
  await page.locator(".avatar-button").click();
  await page.getByRole("button", { name: "Log out" }).click();
  await expect(page.getByRole("link", { name: "Log in", exact: true })).toBeVisible();
  await page.goto("/login");
  await page.getByLabel("Work email").fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Log in to your workspace" }).click();
  await expect(page).toHaveURL(/\/map/);
  const forbidden = await request.post("/api/auth/login", { headers: { Origin: "https://untrusted.example" }, data: { email, password } });
  expect(forbidden.status()).toBe(403);
});

test("mobile landing exposes map controls and keeps text below the map", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  await expect(page.locator(".map-loading")).toHaveCount(0, { timeout: 30000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await expect(page.locator(".landing-filter-bar select")).toHaveCount(3);
  await expect(page.getByRole("button", { name: "Zoom in", exact: true })).toBeInViewport();
  await expect(page.getByRole("heading", { name: /Source real-world data/ })).not.toBeInViewport();
  await page.getByRole("button", { name: "Open map filters" }).click();
  await page.getByLabel("Country", { exact: true }).selectOption("Japan");
  await expect(page.getByRole("button", { name: /View .* profile/ }).first()).toBeVisible();
  await page.getByRole("button", { name: "Clear filters" }).click();
  await page.screenshot({ path: "test-results/mobile-landing.png" });
});

test("mobile profile expands and keeps workspaces isolated", async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/signup");
  await page.getByLabel("Full name").fill("Mobile Explorer");
  await page.getByLabel("Work email").fill(`mobile-${Date.now()}@example.test`);
  await page.getByLabel("Password", { exact: true }).fill("MobileTest!2026");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/map/);
  await page.getByRole("textbox", { name: "Search geography, companies, or facilities" }).fill("Tokyo");
  await page.locator(".provider-card").first().click();
  const before = await page.locator(".profile-panel").boundingBox();
  await page.getByRole("button", { name: "Expand profile" }).click();
  await expect(page.getByRole("button", { name: "Collapse profile" })).toBeVisible();
  const after = await page.locator(".profile-panel").boundingBox();
  expect(after!.height).toBeGreaterThan(before!.height);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "Save provider", exact: true }).click();
  await expect(page.getByRole("button", { name: "Unsave provider", exact: true })).toBeVisible();
  const other = await request.post("/api/auth/signup", { headers: { Origin: "http://localhost:3000" }, data: { name: "Other Tester", email: `other-${Date.now()}@example.test`, password: "OtherTest!2026" } });
  expect(other.status()).toBe(201);
  const workspace = await (await request.get("/api/workspace")).json();
  expect(workspace.saved).toEqual([]);
  expect(workspace.requests).toEqual([]);
});
