BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'buyer' CHECK (role IN ('buyer', 'supplier', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'buyer';
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_attempts (
  key TEXT PRIMARY KEY,
  attempts INTEGER NOT NULL,
  reset_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_tokens (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL CHECK (purpose IN ('email_verification', 'password_reset')),
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  attempts INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS email_outbox (
  id UUID PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  recipient_email TEXT NOT NULL,
  purpose TEXT NOT NULL CHECK (purpose IN ('email_verification', 'password_reset', 'password_changed')),
  subject TEXT NOT NULL,
  body_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'processing', 'sent', 'failed')),
  provider_message_id TEXT,
  last_error TEXT,
  attempts INTEGER NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMPTZ
);
ALTER TABLE email_outbox ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE email_outbox ADD COLUMN IF NOT EXISTS available_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE email_outbox DROP CONSTRAINT IF EXISTS email_outbox_status_check;
ALTER TABLE email_outbox ADD CONSTRAINT email_outbox_status_check CHECK (status IN ('queued', 'processing', 'sent', 'failed'));

CREATE TABLE IF NOT EXISTS providers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES users(id) ON DELETE SET NULL,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  provider_type TEXT NOT NULL CHECK (provider_type IN ('Facility', 'Data Company', 'Robotics')),
  modalities JSONB NOT NULL DEFAULT '[]',
  media JSONB NOT NULL DEFAULT '{}',
  profile JSONB NOT NULL DEFAULT '{}',
  verification_level TEXT NOT NULL DEFAULT 'online' CHECK (verification_level IN ('unverified', 'online', 'physical')),
  status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('draft', 'pending', 'approved', 'rejected')),
  is_demo BOOLEAN NOT NULL DEFAULT FALSE,
  profile_views INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE providers ADD COLUMN IF NOT EXISTS is_demo BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE providers SET is_demo = TRUE WHERE owner_id IS NULL;

CREATE TABLE IF NOT EXISTS supplier_applications (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  application_kind TEXT NOT NULL DEFAULT 'company' CHECK (application_kind IN ('company', 'facility')),
  business_name TEXT NOT NULL,
  maps_url TEXT,
  physical_address TEXT,
  city TEXT,
  country TEXT,
  longitude DOUBLE PRECISION,
  latitude DOUBLE PRECISION,
    hardware_pictures JSONB NOT NULL DEFAULT '[]',
    office_images JSONB NOT NULL DEFAULT '[]',
    official_documents JSONB NOT NULL DEFAULT '[]',
  linkedin_url TEXT,
  twitter_url TEXT,
  huggingface_url TEXT,
  website_url TEXT,
  provider_type TEXT NOT NULL CHECK (provider_type IN ('Facility', 'Data Company', 'Robotics')),
  modalities JSONB NOT NULL DEFAULT '[]',
  robotics_types JSONB NOT NULL DEFAULT '[]',
  profile_description TEXT NOT NULL DEFAULT '',
  capacity TEXT NOT NULL DEFAULT '',
  capture_environments JSONB NOT NULL DEFAULT '[]',
  provider_slug TEXT,
  sample_file_name TEXT,
  sample_mime_type TEXT,
  sample_size_bytes INTEGER,
  sample_data BYTEA,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('draft', 'pending', 'approved', 'rejected')),
  verification_level TEXT NOT NULL DEFAULT 'unverified' CHECK (verification_level IN ('unverified', 'online', 'physical')),
  admin_notes TEXT,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
);
ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS application_kind TEXT NOT NULL DEFAULT 'company';
UPDATE supplier_applications SET application_kind = CASE WHEN provider_type = 'Data Company' THEN 'company' ELSE 'facility' END;
ALTER TABLE supplier_applications DROP CONSTRAINT IF EXISTS supplier_applications_application_kind_check;
ALTER TABLE supplier_applications ADD CONSTRAINT supplier_applications_application_kind_check CHECK (application_kind IN ('company', 'facility'));
ALTER TABLE supplier_applications ALTER COLUMN maps_url DROP NOT NULL;
ALTER TABLE supplier_applications ALTER COLUMN physical_address DROP NOT NULL;
ALTER TABLE supplier_applications ALTER COLUMN city DROP NOT NULL;
ALTER TABLE supplier_applications ALTER COLUMN country DROP NOT NULL;
ALTER TABLE supplier_applications ALTER COLUMN longitude DROP NOT NULL;
ALTER TABLE supplier_applications ALTER COLUMN latitude DROP NOT NULL;
  ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS profile_description TEXT NOT NULL DEFAULT '';
  ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS office_images JSONB NOT NULL DEFAULT '[]';
  ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS official_documents JSONB NOT NULL DEFAULT '[]';
ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS capacity TEXT NOT NULL DEFAULT '';
ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS capture_environments JSONB NOT NULL DEFAULT '[]';
ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS provider_slug TEXT;
ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS sample_file_name TEXT;
ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS sample_mime_type TEXT;
ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS sample_size_bytes INTEGER;
ALTER TABLE supplier_applications ADD COLUMN IF NOT EXISTS sample_data BYTEA;
UPDATE supplier_applications
SET provider_slug = TRIM(BOTH '-' FROM REGEXP_REPLACE(LOWER(business_name), '[^a-z0-9]+', '-', 'g')) || '-' || LEFT(id::text, 6)
WHERE application_kind = 'facility' AND provider_slug IS NULL;

CREATE TABLE IF NOT EXISTS saved_operators (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  operator_slug TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY(user_id, operator_slug)
);
ALTER TABLE saved_operators ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS access_requests (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  operator_slug TEXT NOT NULL,
  purpose TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, operator_slug)
);
ALTER TABLE access_requests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE access_requests ALTER COLUMN status SET DEFAULT 'pending';
UPDATE access_requests SET status = LOWER(status) WHERE status <> LOWER(status);

CREATE TABLE IF NOT EXISTS conversations (
  id UUID PRIMARY KEY,
  buyer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  supplier_id UUID REFERENCES users(id) ON DELETE CASCADE,
  operator_slug TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(buyer_id, supplier_id, operator_slug)
);

CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS concierge_requests (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  brief TEXT NOT NULL,
  budget TEXT,
  timeline TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE concierge_requests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS integration_outbox (
  id UUID PRIMARY KEY,
  event_type TEXT NOT NULL CHECK (event_type IN ('user.sheet.upsert')),
  entity_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  attempts INTEGER NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  UNIQUE(event_type, entity_id)
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id UUID PRIMARY KEY,
  admin_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);
CREATE INDEX IF NOT EXISTS auth_tokens_user_purpose_idx ON auth_tokens(user_id, purpose, created_at DESC);
CREATE INDEX IF NOT EXISTS auth_tokens_expires_idx ON auth_tokens(expires_at);
CREATE INDEX IF NOT EXISTS email_outbox_status_idx ON email_outbox(status, available_at, created_at);
CREATE INDEX IF NOT EXISTS email_outbox_ready_idx ON email_outbox(status, available_at, created_at);
CREATE INDEX IF NOT EXISTS providers_status_idx ON providers(status, verification_level);
CREATE INDEX IF NOT EXISTS applications_status_idx ON supplier_applications(status);
CREATE INDEX IF NOT EXISTS applications_user_kind_idx ON supplier_applications(user_id, application_kind, submitted_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS applications_provider_slug_idx ON supplier_applications(provider_slug) WHERE provider_slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS messages_conversation_idx ON messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS access_requests_operator_idx ON access_requests(operator_slug, created_at DESC);
CREATE INDEX IF NOT EXISTS concierge_requests_status_idx ON concierge_requests(status, created_at DESC);
CREATE INDEX IF NOT EXISTS integration_outbox_ready_idx ON integration_outbox(status, available_at, created_at);
CREATE INDEX IF NOT EXISTS admin_audit_logs_created_idx ON admin_audit_logs(created_at DESC);

COMMIT;
