"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Building2, Check, Eye, EyeOff, Image as ImageIcon, LoaderCircle, MapPinned, Mic, Radio, ShieldCheck, Video } from "lucide-react";
import PublicNavigationRail from "./PublicNavigationRail";
import FacilityLocationPicker from "./FacilityLocationPicker";
import type { PickedLocation } from "./FacilityLocationPicker";
import { api } from "./model";
import OfficeImagePicker, { type OfficeImage } from "./OfficeImagePicker";
import OfficialDocumentPicker, { type OfficialDocument } from "./OfficialDocumentPicker";

const capabilities = [{ value: "Egocentric video", icon: Video, detail: "First-person capture" }, { value: "Exocentric video", icon: Radio, detail: "Third-person capture" }, { value: "Speech", icon: Mic, detail: "Voice and conversation" }, { value: "Images", icon: ImageIcon, detail: "Image datasets" }];
const focusCards = [{ value: "collection", title: "Data collection", detail: "Capture and collection operations" }, { value: "platform", title: "Data platform", detail: "Data products and infrastructure" }, { value: "embodied", title: "Embodied AI", detail: "Robotics and real-world AI" }];
const initialValues = { name: "", email: "", password: "", confirmation: "", businessName: "", description: "", websiteUrl: "", mapsUrl: "", physicalAddress: "", city: "", country: "", longitude: "", latitude: "", focus: "collection", modalities: [] as string[] };
const steps = ["Company profile & evidence", "Data capabilities", "Company location", "Account setup"];
type UploadedAsset = { url: string; name: string; contentType: string; file?: File };

async function persistAssets(kind: "office" | "document", assets: UploadedAsset[], documentType = "") {
  if (!assets.length) return;
  const body = new FormData(); body.set("kind", kind); if (documentType) body.set("documentType", documentType);
  assets.forEach((asset) => { if (asset.file) body.append("files", asset.file); });
  const response = await fetch("/api/company-assets", { method: "POST", body });
  const data = await response.json() as { error?: string };
  if (!response.ok) throw new Error(data.error || "Your account was created, but the evidence upload could not finish.");
}

export default function DataCompanySignupForm() {
  const [step, setStep] = useState(0); const [profileStage, setProfileStage] = useState<0 | 1>(0); const [values, setValues] = useState(initialValues);
  const [officeImages, setOfficeImages] = useState<OfficeImage[]>([]); const [documents, setDocuments] = useState<OfficialDocument[]>([]);
  const [showPasswords, setShowPasswords] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const router = useRouter();
  const update = (field: keyof typeof initialValues, value: string | string[]) => setValues((current) => ({ ...current, [field]: value }));
  const toggleModality = (value: string) => update("modalities", values.modalities.includes(value) ? values.modalities.filter((item) => item !== value) : [...values.modalities, value]);
  const applyLocation = (location: PickedLocation) => setValues((current) => ({ ...current, longitude: String(location.longitude), latitude: String(location.latitude), mapsUrl: location.mapsUrl || `https://www.google.com/maps/search/?api=1&query=${location.latitude},${location.longitude}`, physicalAddress: location.label || current.physicalAddress, city: location.city || current.city, country: location.country || current.country }));
  const validateStep = () => {
    if (step === 0 && profileStage === 0 && (values.businessName.trim().length < 2 || values.description.trim().length < 20)) return "Add your company name and a short description of at least 20 characters.";
    if (step === 0 && profileStage === 1 && documents.some((document) => document.type.trim().length < 2)) return "Add a document type for every official document.";
    if (step === 1 && values.modalities.length === 0) return "Choose at least one data capability.";
    if (step === 2 && (!values.websiteUrl || !values.mapsUrl || values.physicalAddress.trim().length < 5 || values.city.trim().length < 2 || values.country.trim().length < 2 || !values.longitude || !values.latitude)) return "Search for or pin the company location, then confirm the address details.";
    if (step === 3 && (values.name.trim().length < 2 || !values.email || values.password.length < 12 || values.password !== values.confirmation)) return "Complete your account details and use matching 12-character passwords.";
    return "";
  };
  const passwordScore = [values.password.length >= 12, /[a-z]/.test(values.password), /[A-Z]/.test(values.password), /\d/.test(values.password), /[^A-Za-z0-9]/.test(values.password)].filter(Boolean).length;
  const next = () => { const message = validateStep(); if (message) { setError(message); return; } if (step === 0 && profileStage === 0) { setError(""); setProfileStage(1); return; } setError(""); setStep((current) => Math.min(current + 1, 3)); };
  const back = () => { setError(""); if (step === 0 && profileStage === 1) setProfileStage(0); else setStep((current) => Math.max(current - 1, 0)); };
  const submit = async () => { const message = validateStep(); if (message) { setError(message); return; } setBusy(true); setError(""); try { await api("/api/auth/signup", { method: "POST", body: JSON.stringify({ ...values, role: "supplier", companyApplication: true }) }); await persistAssets("office", officeImages); for (const document of documents) await persistAssets("document", [document], document.type.trim()); router.push("/verify-email"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to submit your company application."); } finally { setBusy(false); } };
  const titles = [profileStage === 0 ? "Tell us about your company" : "Add office images and official documents", "What data can you provide?", "Where is your company located?", "Create your secure account"];
  const descriptions = [profileStage === 0 ? "Start with the public-facing details buyers and reviewers should understand." : "Help us validate your company with office images and official company documents. These are only visible to reviewers.", "Choose each capability your company can supply today.", "Search an address, paste a Google Maps location, or place the pin exactly where your company is based.", "Use a business email to receive your verification link and review updates."];
  return <main className="sourcing-app company-signup-page"><PublicNavigationRail active="supplier-signup"/><section className="company-wizard company-wizard-full" aria-labelledby="company-wizard-title"><header className="company-wizard-banner"><span className="company-wizard-mark"><MapPinned/></span><div><p>MAP.FILEMARKET</p><h1 id="company-wizard-title">Register your data company.</h1></div><span>Application · 4 steps</span></header><form className="company-wizard-form" onSubmit={(event) => { event.preventDefault(); if (step === 3) void submit(); else next(); }}><header><span>STEP {step + 1} OF 4{step === 0 ? ` · ${profileStage + 1} OF 2` : ""}</span><h2>{titles[step]}</h2><p>{descriptions[step]}</p></header><div className="company-wizard-content">
    {step === 0 && profileStage === 0 && <div className="company-wizard-fields"><label className="wizard-input-card"><span>Company name</span><input value={values.businessName} onChange={(event) => update("businessName", event.target.value)} autoComplete="organization" placeholder="Your company name" autoFocus/></label><label className="wizard-input-card"><span>Company profile</span><textarea value={values.description} onChange={(event) => update("description", event.target.value)} placeholder="What data do you provide, and how is it collected?"/></label><div><span className="wizard-section-label">Primary focus</span><div className="wizard-choice-grid">{focusCards.map((card) => <button type="button" key={card.value} className={values.focus === card.value ? "selected" : ""} onClick={() => update("focus", card.value)}><Building2/><strong>{card.title}</strong><small>{card.detail}</small>{values.focus === card.value && <Check/>}</button>)}</div></div></div>}
{step === 0 && profileStage === 1 && <div className="company-wizard-fields company-evidence-fields"><OfficeImagePicker images={officeImages} onChange={setOfficeImages} onError={setError}/><OfficialDocumentPicker documents={documents} onChange={setDocuments} onError={setError}/></div>}
    {step === 1 && <div><span className="wizard-section-label">Select all that apply</span><div className="wizard-capability-grid">{capabilities.map(({ value, icon: Icon, detail }) => <button type="button" key={value} className={values.modalities.includes(value) ? "selected" : ""} onClick={() => toggleModality(value)}><Icon/><span><strong>{value}</strong><small>{detail}</small></span>{values.modalities.includes(value) && <i><Check/></i>}</button>)}</div></div>}
    {step === 2 && <div className="company-wizard-fields"><label className="wizard-input-card"><span>Company website</span><input type="url" value={values.websiteUrl} onChange={(event) => update("websiteUrl", event.target.value)} placeholder="https://company.com"/></label><div className="wizard-location-picker"><span className="wizard-section-label">Find or pinpoint your company</span><FacilityLocationPicker longitude={values.longitude} latitude={values.latitude} onChange={applyLocation}/></div><div className="wizard-field-grid"><label className="wizard-input-card"><span>Physical address</span><input value={values.physicalAddress} onChange={(event) => update("physicalAddress", event.target.value)} placeholder="Street address"/></label><label className="wizard-input-card"><span>Google Maps location</span><input type="url" value={values.mapsUrl} onChange={(event) => update("mapsUrl", event.target.value)} placeholder="Added when you search or pin a location"/></label></div><div className="wizard-field-grid">{[["city", "City", "Kathmandu"], ["country", "Country", "Nepal"], ["longitude", "Longitude", "85.3240"], ["latitude", "Latitude", "27.7172"]].map(([field, label, placeholder]) => <label className="wizard-input-card" key={field}><span>{label}</span><input readOnly={field === "longitude" || field === "latitude"} value={values[field as "city" | "country" | "longitude" | "latitude"]} onChange={(event) => update(field as "city" | "country" | "longitude" | "latitude", event.target.value)} placeholder={placeholder}/></label>)}</div><p className="wizard-location-note"><MapPinned/> We use the exact pin only to verify your company location before it appears on the map.</p></div>}
    {step === 3 && <div className="company-wizard-fields"><div className="wizard-field-grid">{[["name", "Your name", "Alex Morgan", "text"], ["email", "Business email", "you@company.com", "email"], ["password", "Password", "12+ characters", "password"], ["confirmation", "Confirm password", "Type it again", "password"]].map(([field, label, placeholder, type]) => <label className="wizard-input-card" key={field}><span>{label}</span><div className="wizard-password-input"><input type={type === "password" && showPasswords ? "text" : type} value={values[field as "name" | "email" | "password" | "confirmation"]} onChange={(event) => update(field as "name" | "email" | "password" | "confirmation", event.target.value)} autoComplete={field === "email" ? "email" : field === "name" ? "name" : "new-password"} placeholder={placeholder} autoFocus={field === "name"}/>{type === "password" && <button type="button" aria-label={showPasswords ? "Hide password" : "Show password"} onClick={() => setShowPasswords((current) => !current)}>{showPasswords ? <EyeOff/> : <Eye/>}</button>}</div></label>)}</div><div className="wizard-password-strength" aria-live="polite"><span><b>Password strength</b><small>{values.password ? (passwordScore < 3 ? "Needs strengthening" : passwordScore < 5 ? "Good password" : "Strong password") : "Use 12+ characters with a mix of letters, numbers, and symbols."}</small></span><div>{[1, 2, 3, 4, 5].map((level) => <i key={level} className={level <= passwordScore ? `active score-${passwordScore}` : ""}/>)}</div></div><div className="wizard-trust-card"><ShieldCheck/><span><strong>What happens next</strong><small>We email a verification link, then your company application is marked pending for review.</small></span></div></div>}
  </div>{error && <p className="company-wizard-error" role="alert">{error}</p>}<footer><div className="company-wizard-progress" aria-label={`Step ${step + 1} of 4`}><span>Application progress</span><div>{steps.map((label, index) => <i key={label} className={index <= step ? "active" : ""} title={label}/>)}</div><small>{steps[step]}{step === 0 ? ` · ${profileStage + 1} of 2` : ""}</small></div><div className="company-wizard-actions">{(step > 0 || profileStage > 0) && <button type="button" className="wizard-back" onClick={back}><ArrowLeft/>Back</button>}<button type="submit" className="wizard-next" disabled={busy}>{busy ? <LoaderCircle className="spin"/> : step === 3 ? <><ShieldCheck/>Submit application</> : <>Continue<ArrowRight/></>}</button></div></footer><p className="company-wizard-login">Already registered? <Link href="/login">Log in</Link></p></form></section>
  </main>;
}
