import "server-only";

import { JWT } from "google-auth-library";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { query } from "@/lib/db/client";

type SheetDefinition = { title: string; id: string; headers: string[]; sql: string };
const worksheet = (variable: string, fallback: string) => process.env[variable]?.trim() || fallback;
const sheets: SheetDefinition[] = [
  { title: worksheet("GOOGLE_SHEETS_USERS_WORKSHEET", "Users"), id: "user_id", headers: ["user_id", "full_name", "email", "role", "email_verified", "registered_at", "password_changed_at", "last_synced_at"], sql: "SELECT id AS user_id, name AS full_name, email, role, CASE WHEN email_verified_at IS NULL THEN 'No' ELSE 'Yes' END AS email_verified, created_at AS registered_at, password_changed_at FROM users ORDER BY created_at ASC" },
  { title: worksheet("GOOGLE_SHEETS_COMPANIES_WORKSHEET", "Data Companies"), id: "application_id", headers: ["application_id", "supplier_user_id", "company_name", "google_maps_url", "physical_address", "city", "country", "longitude", "latitude", "website_url", "linkedin_url", "twitter_url", "huggingface_url", "modalities", "profile_description", "google_maps_photo_urls", "sample_file_name", "sample_size_bytes", "application_status", "verification_level", "admin_notes", "submitted_at", "reviewed_at", "provider_slug", "provider_status", "provider_created_at", "last_synced_at"], sql: "SELECT applications.id AS application_id, applications.user_id AS supplier_user_id, applications.business_name AS company_name, applications.maps_url AS google_maps_url, applications.physical_address, applications.city, applications.country, applications.longitude, applications.latitude, applications.website_url, applications.linkedin_url, applications.twitter_url, applications.huggingface_url, applications.modalities, applications.profile_description, applications.hardware_pictures AS google_maps_photo_urls, applications.sample_file_name, applications.sample_size_bytes, applications.status AS application_status, applications.verification_level, applications.admin_notes, applications.submitted_at, applications.reviewed_at, applications.provider_slug, providers.status AS provider_status, providers.created_at AS provider_created_at FROM supplier_applications applications LEFT JOIN providers ON providers.slug = applications.provider_slug WHERE applications.application_kind = 'company' ORDER BY applications.submitted_at ASC" },
  { title: worksheet("GOOGLE_SHEETS_FACILITIES_WORKSHEET", "Facilities"), id: "application_id", headers: ["application_id", "supplier_user_id", "facility_name", "google_maps_url", "physical_address", "city", "country", "longitude", "latitude", "modalities", "profile_description", "collection_capacity", "capture_environments", "photo_urls", "application_status", "verification_level", "admin_notes", "submitted_at", "reviewed_at", "provider_slug", "provider_status", "provider_created_at", "last_synced_at"], sql: "SELECT applications.id AS application_id, applications.user_id AS supplier_user_id, applications.business_name AS facility_name, applications.maps_url AS google_maps_url, applications.physical_address, applications.city, applications.country, applications.longitude, applications.latitude, applications.modalities, applications.profile_description, applications.capacity AS collection_capacity, applications.capture_environments, applications.hardware_pictures AS photo_urls, applications.status AS application_status, applications.verification_level, applications.admin_notes, applications.submitted_at, applications.reviewed_at, applications.provider_slug, providers.status AS provider_status, providers.created_at AS provider_created_at FROM supplier_applications applications LEFT JOIN providers ON providers.slug = applications.provider_slug WHERE applications.application_kind = 'facility' ORDER BY applications.submitted_at ASC" },
  { title: worksheet("GOOGLE_SHEETS_DATA_REQUESTS_WORKSHEET", "Data Requests"), id: "request_id", headers: ["request_id", "buyer_user_id", "buyer_name", "buyer_email", "provider_slug", "provider_name", "purpose", "status", "requested_at", "updated_at", "last_synced_at"], sql: "SELECT requests.id AS request_id, requests.user_id AS buyer_user_id, users.name AS buyer_name, users.email AS buyer_email, requests.operator_slug AS provider_slug, providers.name AS provider_name, requests.purpose, requests.status, requests.created_at AS requested_at, requests.updated_at FROM access_requests requests JOIN users ON users.id = requests.user_id LEFT JOIN providers ON providers.slug = requests.operator_slug ORDER BY requests.created_at ASC" },
  { title: worksheet("GOOGLE_SHEETS_CONCIERGE_WORKSHEET", "Concierge Briefs"), id: "brief_id", headers: ["brief_id", "buyer_user_id", "buyer_name", "buyer_email", "project_brief", "budget", "timeline", "status", "submitted_at", "updated_at", "last_synced_at"], sql: "SELECT requests.id AS brief_id, requests.user_id AS buyer_user_id, users.name AS buyer_name, users.email AS buyer_email, requests.brief AS project_brief, requests.budget, requests.timeline, requests.status, requests.created_at AS submitted_at, requests.updated_at FROM concierge_requests requests JOIN users ON users.id = requests.user_id ORDER BY requests.created_at ASC" },
  { title: worksheet("GOOGLE_SHEETS_SAVED_PROVIDERS_WORKSHEET", "Saved Providers"), id: "saved_provider_id", headers: ["saved_provider_id", "buyer_user_id", "buyer_name", "buyer_email", "provider_slug", "provider_name", "saved_at", "last_synced_at"], sql: "SELECT saved.user_id || ':' || saved.operator_slug AS saved_provider_id, saved.user_id AS buyer_user_id, users.name AS buyer_name, users.email AS buyer_email, saved.operator_slug AS provider_slug, providers.name AS provider_name, saved.created_at AS saved_at FROM saved_operators saved JOIN users ON users.id = saved.user_id LEFT JOIN providers ON providers.slug = saved.operator_slug ORDER BY saved.created_at ASC" },
];
function safeCell(value: unknown) { if (value === null || value === undefined) return ""; const text = (typeof value === "object" ? JSON.stringify(value) : String(value)).replace(/[\u0000-\u001F\u007F]/g, " ").trim(); return /^[=+\-@]/.test(text) ? `'${text}` : text; }

export async function synchronizeGoogleSheets() {
  const spreadsheetId = process.env.GOOGLE_SHEETS_SPREADSHEET_ID;
  const email = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
  const privateKey = process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY;
  if (!spreadsheetId || !email || !privateKey) throw new Error("Google Sheets integration is not configured.");
  const auth = new JWT({ email, key: privateKey.replace(/\\n/g, "\n"), scopes: ["https://www.googleapis.com/auth/spreadsheets"] });
  const document = new GoogleSpreadsheet(spreadsheetId, auth);
  await document.loadInfo();
  const syncedAt = new Date().toISOString(); const result: Record<string, number> = {};
  for (const definition of sheets) {
    let sheet = document.sheetsByTitle[definition.title];
    if (!sheet) sheet = await document.addSheet({ title: definition.title, headerValues: definition.headers, gridProperties: { rowCount: 1_000, columnCount: definition.headers.length } });
    else { try { await sheet.loadHeaderRow(); } catch { await sheet.resize({ rowCount: sheet.rowCount, columnCount: definition.headers.length }); await sheet.setHeaderRow(definition.headers); } const absent = definition.headers.filter((header) => !sheet.headerValues.includes(header)); if (absent.length) throw new Error(`Worksheet ${definition.title} is missing headers: ${absent.join(", ")}.`); }
    const source = await query(definition.sql);
    const rows = source.rows.map((row) => Object.fromEntries(definition.headers.map((header) => [header, header === "last_synced_at" ? syncedAt : safeCell(row[header])]))) as Record<string, string>[];
    const existing = await sheet.getRows({ limit: 50_000 }); const existingById = new Map(existing.map((row) => [String(row.get(definition.id)), row])); const currentIds = new Set(rows.map((row) => row[definition.id]));
    for (const values of rows) { const row = existingById.get(values[definition.id]); if (row) { row.assign(values); await row.save({ raw: true }); } else await sheet.addRow(values, { raw: true }); }
    for (const row of existing) if (!currentIds.has(String(row.get(definition.id)))) await row.delete();
    result[definition.title] = rows.length;
  }
  await query("UPDATE integration_outbox SET status = 'completed', processed_at = NOW(), last_error = NULL WHERE event_type = 'user.sheet.upsert' AND status IN ('pending', 'failed', 'processing')");
  return result;
}
